version: '3.1'

services:
  mongodb:
    image: mongo
    container_name: mongodb_container
    ports:
      - "27017:27017"


  java_app:
    image: openjdk:20
    container_name: java_app_container
    ports:
      - "8080:8080"
    volumes:
      - /Users/svetislavdobromirov/working/AutoDocFiller/FilerSpring/target/FilerSpring-0.0.1-SNAPSHOT.jar:/app/app.jar
    command: ["java", "-jar", "/app/app.jar"]
    depends_on:
      - mongodb
#    networks:
#      - filler_network

    environment:
      - MONGO=mongodb

